M48
; DRILL file {KiCad 8.0.8} date 2025-08-25T22:33:12+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-25T22:33:12+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X35.0Y-84.0
X70.1Y-23.5
X70.1Y-43.3
X89.9Y-23.5
X89.9Y-43.3
X125.0Y-84.0
M30
